version: "3.5"

services:
  web:
    container_name: dockerdev
    build: ./
    ports:
      - "8080:8080"
    environment:
      DD_DB_HOST: db
    command: ./goapp -logtostderr=true
    depends_on:
      - db
    volumes:
      - ./template:/app/template
      - ./static:/app/static
  db:
    container_name: dockerdev-db
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql