apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  # property-like keys; each key maps to a simple value
  db_name: "observe"
  db_host: "postgres-loadbalancer.default.svc.cluster.local"
  db_port: "5432"
