apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
      - kubernetes.local
    secretName: test-cert
  defaultBackend:
    service:
      name: go-observe-service
      port:
        number: 8080

#  rules:
#    - host: kubernetes.local
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: go-observe-service
#                port:
#                  number: 8080